set(DANTE_VERSION_MAJOR 1)
set(DANTE_VERSION_MINOR 0)
set(DANTE_VERSION_PATCH 22)
set(DANTE_VERSION "${DANTE_VERSION_MAJOR}.${DANTE_VERSION_MINOR}.${DANTE_VERSION_PATCH}")

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE DANTE_GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(NOT DANTE_GIT_HASH)
    set(DANTE_GIT_HASH "unknown")
endif()

set(DANTE_BUILD_ID "${DANTE_VERSION}+${DANTE_GIT_HASH}")
